apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 975050086565.dkr.ecr.eu-north-1.amazonaws.com/test-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
        env:                              
        - name: CPU_LOAD
          value: "yes"
